name: Code Quality
# https://medium.com/swlh/enhancing-code-quality-with-github-actions-67561c6f7063

permissions:
  checks: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          sudo apt-get install -y libmariadb-dev
          python -m pip install --upgrade pip

      - name: Install Python linters
        run: pip install flake8 pylint

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          flake8_args: |
            --ignore=E501,F821
          continue_on_error: false
          pylint: true
          # https://github.com/pylint-dev/pylint/issues/8138
          pylint_args: |
            --disable=missing-class-docstring \
            --disable=missing-function-docstring \
            --disable=line-too-long \
            --disable=too-few-public-methods \
            --disable=W0511 \
            --disable=W0621 \
            --disable=W0622 \
            --disable=E1102 \
            --disable=C0103 \
            --disable=R1732 \
            --disable=R1710 \
            --disable=R0801 \
            --extension-pkg-whitelist=pydantic
  lint_go:
    runs-on: ubuntu-latest
    steps:
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          working-directory: /2024/Day01
